---

owner: RecoveryDharma
repo: status

sites:
    -
        name: 🕸 Recovery Dharma Global site
        url: https://RecoveryDharma.org/
        assignees:
            - nutjob4life
            - tom-raley
    -
        name: 🎟 Sangha Summit ticketing
        url: https://recoverydharma.simpletix.com/
        assignees:
            - tom-raley
            - nutjob4life

status-website:
    baseUrl: /status
    logoUrl: https://raw.githubusercontent.com/RecoveryDharma/status/master/assets/cog.svg
    name: RD Global Status
    introTitle: "**Status** of Recovery Dharma systems"
    introMessage: >
        The status of Recovery Dharma Global IT systems, websites, etc. is presented below.
    theme: light
    navbar:
        -
            title: Status
            href: /status
        -
            title: GitHub
            href: https://github.com/$OWNER/$REPO

skipDescriptionUpdate: true
skipTopicsUpdate: true

...

# -*- mode: YAML; tab-width: 4 -*-
